# Generated by Django 4.2.1 on 2023-06-26 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_korisnici_uloga_delete_uloga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uloga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'admin'), ('PROFESOR', 'profesor'), ('STUDENT', 'student')], default='STUDENT', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='korisnici',
            name='uloga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.uloga'),
        ),
    ]
