# Generated by Django 4.2.1 on 2023-06-26 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_uloga_role_alter_korisnici_uloga'),
    ]

    operations = [
        migrations.AddField(
            model_name='uloga',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('PROFESOR', 'profesor'), ('STUDENT', 'student')], default='STUDENT', max_length=50),
        ),
        migrations.AlterField(
            model_name='korisnici',
            name='uloga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.uloga'),
        ),
    ]
