# Generated by Django 4.2.1 on 2023-06-27 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_uloga_role_alter_korisnici_uloga'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uloga',
        ),
    ]
